sudo: false

language: node_js

cache:
  directories:
    - node_modules
    - $HOME/.npm
    - $HOME/.yarn-cache

notifications:
  email: false

node_js:
  - 4
  - 5
  - 6
  - 7

before_install:
  - npm i -g npm
  - npm i -g yarn
  - yarn

before_script:
  - npm prune

script:
  - npm test

after_success:
  - 'curl -Lo travis_after_all.py https://git.io/travis_after_all'
  - python travis_after_all.py
  - export $(cat .to_export_back) &> /dev/null
  - npm run semantic-release
